language: node_js

node_js: stable

branches:
  only:
    - hexo

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "royalbluewa3"
  - git config user.email "royalbluewa3@foxmail.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

env:
  global:
   - GH_REF: github.com/royalbluewa3/royalbluewa3.github.io.git
